import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from './components/Navbar'
import Footer from './components/Footer'
import Provider from './components/Provider'
import { Toaster } from 'react-hot-toast'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Shiv-trading',
  description: 'Generated by create next app',
  icons: 'icon',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Provider>
        <body className={inter.className}>
          <Navbar />
          {children}
          <Toaster 
          toastOptions={{
            style: {
              marginTop:"62px",
              },
            }} 
          position='top-right'/>
          <Footer />
        </body>
      </Provider>
    </html>
  )
}
